DROP TABLE IF EXISTS `comment`;

CREATE TABLE `comment` (`id` INT NOT NULL AUTO_INCREMENT,`name` VARCHAR(20) NOT NULL,`email` VARCHAR(20) NOT NULL,`website` VARCHAR(64) NOT NULL,`comment` VARCHAR(256) NOT NULL,`sex` INT NOT NULL, `commentDate` DATE NOT NULL,
PRIMARY KEY(`id`));